export const specializationIcons: Record<string, string> = {
  'internal-medicine': 'mdi-briefcase-medical',
  ent: 'mdi-ear-hearing',
  cardiology: 'mdi-heart-pulse',
  ophthalmology: 'mdi-eye',
  dermatology: 'mdi-emoticon-outline',
  neurology: 'mdi-brain',
  'general-surgery': 'mdi-content-cut',
  orthopedics: 'mdi-bone',
  gynecology: 'mdi-account-group',
  pediatrics: 'mdi-baby-face-outline',
  oncology: 'mdi-microscope',
  nephrology: 'mdi-water',
  gastroenterology: 'mdi-food-apple',
  endocrinology: 'mdi-chart-bell-curve',
  'plastic-surgery': 'mdi-face-man-shimmer',
  neurosurgery: 'mdi-brain',
  anesthesiology: 'mdi-needle',
  'family-medicine': 'mdi-hospital-building',
  psychiatry: 'mdi-brain',
  'infectious-disease': 'mdi-shield-alert',
  radiology: 'mdi-radioactive',
  emergency: 'mdi-heart-pulse',
  rheumatology: 'mdi-human-cane',
  pulmonology: 'mdi-weather-windy',
  'occupational-medicine': 'mdi-briefcase-medical',
  'sports-medicine': 'mdi-dumbbell',
  hematology: 'mdi-water',
  physiotherapy: 'mdi-human-cane',
  nutrition: 'mdi-food-apple',
  'speech-therapy': 'mdi-message-text-outline',
  urology: 'mdi-water-pump',
  'vascular-surgery': 'mdi-blood-bag',
  'thoracic-surgery': 'mdi-lungs',
  'cardiac-surgery': 'mdi-heart-plus',
  dentistry: 'mdi-tooth',
  orthodontics: 'mdi-tooth-outline',
  'oral-surgery': 'mdi-toothbrush',
  'allergy-immunology': 'mdi-shield-check',
  'nuclear-medicine': 'mdi-atom',
  'intensive-care': 'mdi-hospital-box',
  rehabilitation: 'mdi-wheelchair-accessibility',
  geriatrics: 'mdi-human-cane',
  'forensic-medicine': 'mdi-file-search',
  'medical-genetics': 'mdi-dna',
  pharmacy: 'mdi-pill',
  laboratory: 'mdi-test-tube',
  vaccination: 'mdi-needle',
  ambulance: 'mdi-ambulance',
  hospital: 'mdi-hospital-building',
  'medical-bag': 'mdi-medical-bag',
  surgery: 'mdi-doctor',
  'health-check': 'mdi-clipboard-pulse',
  'mental-health': 'mdi-head-heart',
  'womens-health': 'mdi-gender-female',
  'mens-health': 'mdi-gender-male',
  'primary-care': 'mdi-account-heart',
  'pain-management': 'mdi-bandage',
  'sleep-medicine': 'mdi-sleep',
  'public-health': 'mdi-earth',
}

export const specializationIconOptions = Object.entries(specializationIcons).map(([value, icon]) => ({
  value,
  icon,
}))

export function specializationIcon(iconName?: string): string {
  return specializationIcons[iconName ?? ''] ?? 'mdi-stethoscope'
}
