import type { Component } from 'vue'
import {
  Accessibility,
  Activity,
  Baby,
  Bone,
  Brain,
  BriefcaseMedical,
  Droplets,
  Dumbbell,
  Ear,
  Eye,
  HeartPulse,
  Hospital,
  MessageCircle,
  Microscope,
  Radiation,
  Scissors,
  ShieldAlert,
  Smile,
  Stethoscope,
  Syringe,
  Users,
  Utensils,
  Wind,
} from '@lucide/vue'

const specializationIcons: Record<string, Component> = {
  'internal-medicine': BriefcaseMedical,
  ent: Ear,
  cardiology: HeartPulse,
  ophthalmology: Eye,
  dermatology: Smile,
  neurology: Brain,
  'general-surgery': Scissors,
  orthopedics: Bone,
  gynecology: Users,
  pediatrics: Baby,
  oncology: Microscope,
  nephrology: Droplets,
  gastroenterology: Utensils,
  endocrinology: Activity,
  'plastic-surgery': Smile,
  neurosurgery: Brain,
  anesthesiology: Syringe,
  'family-medicine': Hospital,
  psychiatry: Brain,
  'infectious-disease': ShieldAlert,
  radiology: Radiation,
  emergency: HeartPulse,
  rheumatology: Accessibility,
  pulmonology: Wind,
  'occupational-medicine': BriefcaseMedical,
  'sports-medicine': Dumbbell,
  hematology: Droplets,
  physiotherapy: Accessibility,
  nutrition: Utensils,
  'speech-therapy': MessageCircle,
}

export function specializationIcon(iconName?: string): Component {
  return specializationIcons[iconName ?? ''] ?? Stethoscope
}
